apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-test-app
  template:
    metadata:
      labels:
        app: kubernetes-test-app
    spec:
      containers:
      - name: kubernetes-test-app
        imagePullPolicy: Never # tell Kubernetes not to pull the image from Docker Hub / registry
        image: kubernetes-test-app:latest # use local image
        # imagePullPolicy: Always # tell Kubernetes to pull the image from Docker Hub / registry
        # image: gavis33/kubernetes-test-app:latest # use image from Docker Hub
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
--- #separator
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
spec:
  selector:
    app: kubernetes-test-app
  ports:
  - port: 8080
    targetPort: 5000